name: security

on: [workflow_call]

jobs:
  deps-audit:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-beam-and-install-dependencies
      - run: mix deps.audit --ignore-file=.mix_audit_ignore

  hex-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-beam-and-install-dependencies
      - run: mix hex.audit
