name: test

on: [workflow_call]

jobs:
  unit:
    name: ${{ matrix.elixir }}, ${{ matrix.otp }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - elixir: "1.18"
            otp: "26.x"
          - elixir: "1.18"
            otp: "27.x"
          - elixir: "1.19"
            otp: "28.x"
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-beam-and-install-dependencies
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Run Tests
        run: mix coveralls.json
      - name: Create cover folder
        run: mkdir -p cover
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          files: cover/excoveralls.json
          token: ${{ secrets.CODECOV_TOKEN }}
